Models/Instructor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ITI_Students_Demo.Models
{
    public class Instructor
    {
        public int Id { set; get; }
        [Required]
        public string name { set; get; }

        [ForeignKey("Department")]
        public int? DeptId { get; set; }


        public virtual Department Department { set; get; }
    }
}

Controllers/InstructorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ITI_Students_Demo.Models;

namespace ITI_Students_Demo.Controllers
{
    public class InstructorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Instructors
        [Authorize(Roles = "Ins, Admin")]
        public ActionResult Index()
        {
            var instructors = db.Instructors.Include(i => i.Department);
            return View(instructors.ToList());
        }

        [Authorize(Roles = "Ins, Admin")]
        // GET: Instructors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instructor instructor = db.Instructors.Find(id);
            if (instructor == null)
            {
                return HttpNotFound();
            }
            return View(instructor);
        }

        [Authorize(Roles = "Admin")]
        // GET: Instructors/Create
        public ActionResult Create()
        {
            ViewBag.DeptId = new SelectList(db.Departments, "Id", "DeptName");
            return View();
        }

        // POST: Instructors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,name,DeptId")] Instructor instructor)
        {
            if (ModelState.IsValid)
            {
                db.Instructors.Add(instructor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DeptId = new SelectList(db.Departments, "Id", "DeptName", instructor.DeptId);
            return View(instructor);
        }

        [Authorize(Roles = "Ins")]
        // GET: Instructors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instructor instructor = db.Instructors.Find(id);
            if (instructor == null)
            {
                return HttpNotFound();
            }
            ViewBag.DeptId = new SelectList(db.Departments, "Id", "DeptName", instructor.DeptId);
            return View(instructor);
        }

        // POST: Instructors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,name,DeptId")] Instructor instructor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(instructor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DeptId = new SelectList(db.Departments, "Id", "DeptName", instructor.DeptId);
            return View(instructor);
        }

        [Authorize(Roles = "Admin")]
        // GET: Instructors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instructor instructor = db.Instructors.Find(id);
            if (instructor == null)
            {
                return HttpNotFound();
            }
            return View(instructor);
        }

        // POST: Instructors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Instructor instructor = db.Instructors.Find(id);
            db.Instructors.Remove(instructor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Instructors/Create.cshtml
@model ITI_Students_Demo.Models.Instructor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Instructor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeptId, "DeptId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DeptId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DeptId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Instructors", new { @class = "btn btn-warning" })
</div>

Views/Instructors/Delete.cshtml
@model ITI_Students_Demo.Models.Instructor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.DeptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DeptName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-danger" /> 
     
    @Html.ActionLink("Back to List", "Index", "Instructors", new { @class = "btn btn-warning" })
</div>
    }
</div>

Views/Instructors/Details.cshtml
@model ITI_Students_Demo.Models.Instructor

@{
    ViewBag.Title = "Details";
}



<div>
    <div class="text-center m-3">
        <h2>Details</h2>
        <h4>Instructor</h4>
    </div>
    <div>
        <div class="text-center">
            <div class="d-flex justify-content-center">
                <img src="~/Imgs/noone.png" class="img-fluid img-thumbnail" width="400" height="400"
                     alt="" srcset="">
            </div>
            <p class="h2 m-5">  @Html.DisplayFor(model => model.name)</p>
        </div>

        <div>
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <td>
                            Name
                        </td>
                        <td>
                            Department Name
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td> @Html.DisplayFor(model => model.name)</td>
                        <td>  @Html.DisplayFor(model => model.Department.DeptName)</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class="btn btn-primary" }) 
    @Html.ActionLink("Back to List", "Index", "Instructors", new { @class = "btn btn-warning" })
</p>

Views/Instructors/Edit.cshtml
@model ITI_Students_Demo.Models.Instructor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Instructor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeptId, "DeptId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DeptId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DeptId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index", "Instructor", new { @class = "btn btn-warning" })
</div>

Views/Instructors/Index.cshtml
@model IEnumerable<ITI_Students_Demo.Models.Instructor>

@{
    ViewBag.Title = "Instructors";
}

<h2>Instructors</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr class="thead-light">
        <th>
            @Html.DisplayNameFor(model => model.Department.DeptName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Department.DeptName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td class="text-right">
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }, new { @class = "btn btn-primary" }) 
            @Html.ActionLink("Details", "Details", new { id=item.Id }, new { @class = "btn btn-warning" }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>